[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
aws-config = "1.8.1"
aws-sdk-s3 = "1.91.0"
hex = "0.4.3"
sha2 = "0.10.9"
tokio = {version = "1.46.1", features = ["full"]}
