[package]
name = "metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
async-openai = "0.29.0"
common = { path = "../../crates/common" }
openai = "1.1.1"
regex = "1.11.1"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
